# Generated by Django 6.0.2 on 2026-05-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature_bullets',
            field=models.TextField(blank=True, help_text='One feature or specification per line.'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short product summary for listing previews', max_length=250),
        ),
    ]
